import { Hono } from 'hono';
import { PrismaClient } from '@prisma/client/edge' //not prisma/client, it is prisma/client/edge for the serverless(edge) environment
import { withAccelerate } from '@prisma/extension-accelerate'
import {sign,decode,verify} from "hono/jwt"
import { env } from 'hono/adapter'
import { signupInp,signinInp } from '@alive435/medium-common';
const userRoute = new Hono();

type Bindings={
	DATABASE_URL:string;
	JWT_SECRET:string;
}

userRoute.post('/signup', async (c) => {
	const body = await c.req.json();
	const {success}=signupInp.safeParse(body);
	if(!success){
		c.status(411);
		return c.json({
			message:"inputs not correct"
		})
	}
	const secret=env<Bindings>(c);
	const prisma = new PrismaClient({
		datasourceUrl: secret.DATABASE_URL
	}).$extends(withAccelerate());

	
	try {
		const user = await prisma.user.create({
			data: {
				email: body.email,
				password: body.password,
				name:body.name
			}
		});

		const jwt= await sign({
			id:user.id
		},secret.JWT_SECRET)
		return c.json({user,jwt})
	} catch(e) {
		c.text("invalid cridentials")
		return c.status(403); //unauthorised
	}
	//return c.text('signup route')
})


userRoute.post('/signin', async (c) => {
	const body = await c.req.json();
	const validate=signinInp.safeParse(body);
	if(!validate.success){
		c.status(411);
		return c.json({
			message:validate.error.message
		})
	}
	const secret=env<Bindings>(c);
	const prisma = new PrismaClient({
		datasourceUrl: secret.DATABASE_URL,
	}).$extends(withAccelerate());

	const user = await prisma.user.findUnique({
		where: {
			email: body.email
		}
	});
	if (!user) {
		c.status(403);
		return c.json({ error: "user not found" });
	}
	if(user && user.password!=body.password){
		c.status(411);
		return c.json({message:"incorrect password"});
	}
	const jwt = await sign({ id: user.id }, secret.JWT_SECRET);
    c.text("you are signed in now");
	return c.json({ jwt });
})



export default userRoute;




/*
here index.ts file/backend is not being written in express it is hono(or can say/write in cloudflare), which will eventually access the database
via connection pool. Prisma-accelerate is another offering of prisma that creates connection pool, that connection
pool url put in .toml file is accessed by this file(cloudflare) in order to connect to the database. Here prisma 
client in this edge environment(serverless) is connected with accelerate using the pool url from .toml file.

## Initially hono is given access to the .toml file using Bindings https://hono.dev/getting-started/cloudflare-workers.
context varible c, can be given access to external
## Tyescript begins to complain if dont explicitly define the types of Bindings bcz hono doesn't have the the permission
to the .toml directly,it doesn't know what gonna come environment vriable here .toml file https://hono.dev/helpers/adapter#env https://github.com/honojs/hono/issues/799
## In each route, prisma client is initialised to have autogenerated client which hono use to talk to db, for that 
prisma client connect to db via prisma accelerate(connection pool) using connection pool url.CAN THE PRISMA VARIABLE
BE EXTRACTED OUT IN GLOBAL SCOPE? ofc using middleware
## After each change in the schema file we need to create migration using npm prisma generate dev --name "",
for this prisma looks to .env files to have accces to the db via db url directly
## Then we generate client using npm generate client --no engine, https://console.prisma.io/clw7qpnfy000cw80veen8hs39/clw7r1ozv002ew80v1g6q68ym/clw7r1ozv002fw80vzw1t24mu/accelerate/setup
 */